// frontend/src/lib/components/pages/projects/dashboard/ProjectCard.svelte
<script lang="ts">
    import {
        Avatar,
        AvatarFallback,
        AvatarImage
    } from "$lib/components/ui/avatar";
    import { Badge } from "$lib/components/ui/badge";
    import {
        Card,
        CardContent,
        CardDescription,
        CardHeader,
        CardTitle
    } from "$lib/components/ui/card";
    import { Progress } from "$lib/components/ui/progress";

    import type { Unpacked } from "$lib/utils";
    import type { API } from "$lib/modules/API";

    import { ProjectPriority, ProjectStatus } from "../../../../../../../shared/config/enums";

    const { project }: { project: Unpacked<Awaited<ReturnType<API["fetchProjects"]>>["data"]> } = $props();

    /* eslint-disable svelte/indent */
    let statusColor = $derived(
        project.status === ProjectStatus.Draft
            ? "bg-gray-500"
            : project.status === ProjectStatus.OnHold
                ? "bg-amber-500"
                : project.status === ProjectStatus.Active
                    ? "bg-green-500"
                    : "bg-primary"
    );

    let priorityColor = $derived(
        project.priority === ProjectPriority.High
            ? "bg-red-50 text-red-600 border-red-200"
            : project.priority === ProjectPriority.Medium
                ? "bg-amber-50 text-amber-600 border-amber-200"
                : "bg-green-50 text-green-600 border-green-200"
    );
    /* eslint-enable svelte/indent */
</script>

<Card class="gap-2 cursor-pointer transition-all hover:shadow-lg hover:scale-95 active:scale-90" onclick={() => window.open(`/projects/${project.id}`, "_self")}>
    <CardHeader>
        <div class="flex justify-between items-center">
            <CardTitle class="text-md">{project.title}</CardTitle>
            <CardDescription>
                <Badge class="px-3 py-1 {statusColor}">{project.status}</Badge>
            </CardDescription>
        </div>
    </CardHeader>
    <CardContent>
        <div class="grid grid-cols-2 gap-1">
            <span class="text-xs text-gray-500 font-bold font-manrope uppercase">Due Date</span>
            <span class="text-xs text-gray-500 font-bold font-manrope uppercase">Team</span>
            <span class="text-sm font-semibold">{new Date(project.deadline).toLocaleDateString()}</span>
            <span class="text-sm font-semibold">{project.users.length} {project.users.length === 1 ? "Member" : "Members"}</span>
        </div>
        <div class="flex justify-between items-center mt-4 mb-2">
            <span class="text-xs text-gray-500">Progress</span>
            <span class="text-sm text-primary font-bold">{project.progress}%</span>
        </div>
        <Progress value={project.progress} />
        <div class="flex justify-between items-center mt-4">
            <div class="*:data-[slot=avatar]:ring-background flex -space-x-2 *:data-[slot=avatar]:ring-2">
                {#each project.users as user, i (i)}
                    <Avatar class="size-8">
                        <AvatarImage alt={user} />
                        <AvatarFallback class="text-xs font-semibold">{user.split(" ").slice(0, 1).join("")}</AvatarFallback>
                    </Avatar>
                {/each}
            </div>
            <Badge class="font-semibold uppercase px-2 py-1 {priorityColor}">{project.priority}</Badge>
        </div>
    </CardContent>
</Card>

// frontend/src/components/projectcard.tsx
import React from "react";

// Define the Project type/interface
export interface Project {
    id: number
    title: string
    status: string
    dueDate: string
    teamSize: number
    progress: number
    priority: string
    teamMembers: string[]
}

// Define props for ProjectCard
interface ProjectCardProps {
    project: Project
    onClick?: (project: Project) => void
}

/**
 * ProjectCard Component - Displays a single project card
 */
const ProjectCard: React.FC<ProjectCardProps> = ({ project, onClick }) => {
    return (
        <div
            className="bg-white rounded-xl border border-gray-200 overflow-hidden hover:shadow-lg transition-shadow cursor-pointer"
            onClick={() => onClick && onClick(project)}
        >

            {/* Card content */}
            <div className="p-5">

                {/* Project title and status badge */}
                <div className="flex items-center justify-between mb-4">
                    <h3 className="text-base font-bold text-gray-900">
                        {project.title}
                    </h3>
                    <span
                        className={`text-white text-xs font-semibold px-3 py-1 rounded-full whitespace-nowrap ml-3 ${
                            project.status === "Active"
                                ? "bg-green-500"
                                : project.status === "Planning"
                                    ? "bg-yellow-500"
                                    : project.status === "Completed"
                                        ? "bg-blue-500"
                                        : "bg-gray-500"
                        }`}
                    >
                        {project.status}
                    </span>
                </div>

                {/* Due date and team size */}
                <div className="grid grid-cols-2 gap-4 mb-4">
                    <div>
                        <div className="text-xs font-medium text-gray-500 uppercase mb-1">
                            Due Date
                        </div>
                        <div className="text-sm font-semibold text-gray-900">
                            {project.dueDate}
                        </div>
                    </div>
                    <div>
                        <div className="text-xs font-medium text-gray-500 uppercase mb-1">
                            Team
                        </div>
                        <div className="text-sm font-semibold text-gray-900">
                            {project.teamSize} Members
                        </div>
                    </div>
                </div>

                {/* Progress section */}
                <div className="mb-4">
                    <div className="flex justify-between items-center mb-2">
                        <span className="text-xs font-medium text-gray-600">Progress</span>
                        <span className="text-sm font-bold" style={{ color: "#510087" }}>
                            {project.progress}%
                        </span>
                    </div>
                    {/* Progress bar */}
                    <div className="w-full h-2 bg-gray-200 rounded-full overflow-hidden">
                        <div
                            style={{ width: `${project.progress}%`, backgroundColor: "#510087" }}
                            className="h-full rounded-full"
                        />
                    </div>
                </div>

                {/* Bottom section - avatars and priority */}
                <div className="flex items-center justify-between">

                    {/* Team avatars */}
                    <div className="flex items-center -space-x-2">
                        {project.teamMembers.slice(0, 3).map((member, index) => (
                            <div
                                key={index}
                                className={`w-8 h-8 rounded-full border-2 border-white flex items-center justify-center text-xs font-bold text-white ${
                                    index === 0
                                        ? "bg-red-500"
                                        : index === 1
                                            ? "bg-green-500"
                                            : "bg-yellow-500"
                                }`}
                            >
                                {member}
                            </div>
                        ))}
                        {project.teamMembers.length > 3 && (
                            <div className="w-8 h-8 rounded-full bg-gray-500 border-2 border-white flex items-center justify-center text-xs font-bold text-white">
                                +{project.teamMembers.length - 3}
                            </div>
                        )}
                    </div>

                    {/* Priority badge */}
                    <div
                        className={`px-3 py-1 rounded-full text-xs font-semibold uppercase border ${
                            project.priority === "HIGH"
                                ? "bg-red-50 text-red-600 border-red-200"
                                : project.priority === "MEDIUM"
                                    ? "bg-yellow-50 text-yellow-600 border-yellow-200"
                                    : "bg-green-50 text-green-600 border-green-200"
                        }`}
                    >
                        {project.priority}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ProjectCard;
