// frontend/src/components/layout/Navbar.svelte
<script lang="ts">
    import {
        BellIcon,
        ChevronDownIcon,
        FileText,
        Folder,
        Gauge,
        GraduationCap,
        HamburgerIcon,
        LogOut,
        Mail,
        Settings,
        ShoppingCart,
        User,
        UserCog
    } from "@lucide/svelte";

    import { Avatar, AvatarFallback, AvatarImage } from "$lib/components/ui/avatar";
    import { Badge } from "$lib/components/ui/badge";
    import { Button } from "$lib/components/ui/button";
    import {
        DropdownMenu,
        DropdownMenuContent,
        DropdownMenuItem,
        DropdownMenuLabel,
        DropdownMenuSeparator,
        DropdownMenuTrigger
    } from "$lib/components/ui/dropdown-menu";
    import {
        NavigationMenuRoot,
        NavigationMenuItem,
        NavigationMenuLink,
        NavigationMenuList
    } from "$lib/components/ui/navigation-menu";
    import {
        Popover,
        PopoverContent,
        PopoverTrigger
    } from "$lib/components/ui/popover";

    import LogoImg from "$lib/img/logos/logo.png";
    import { IsMobile } from "$lib/hooks/is-mobile.svelte";

    interface NavbarItem {
        title: string
        href?: string
    }

    const NavigationLinks: NavbarItem[] = [];

    let userName = $state("Car McCarface");
    let userAvatar = $state(null);
    let userEmail = $state("cmccarface1@lsu.edu");
    let notificationCount = $state(0);

    // temp
    const isMobile = false;
</script>

<header class="xl:fixed top-0 z-50 w-full border-b-3 shadow-2xl border-primary bg-background px-4 md:px-6 **:no-underline">
    <div class="flex h-16 items-center justify-between gap-4">
        <div class="flex items-center gap-2">
            {#if isMobile}
                <Popover>
                    <PopoverTrigger>
                        <Button
                            class="group h-9 w-9 hover:bg-accent hover:text-accent-foreground"
                            variant="ghost"
                            size="icon"
                        >
                            <HamburgerIcon />
                        </Button>
                    </PopoverTrigger>
                    <PopoverContent align="start" class="w-64 p-1">
                        <NavigationMenuRoot class="max-w-none">
                            <NavigationMenuList class="flex-col items-start gap-0">
                                {#each NavigationLinks as link, index (index)}
                                    <NavigationMenuItem class="w-full">
                                        <button
                                            onclick={e => {
                                                e.preventDefault();
                                                if (link.href) window.open(link.href, "_blank");
                                            }}
                                            class="flex w-full items-center rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground no-underline"
                                        >
                                            {link.title}
                                        </button>
                                    </NavigationMenuItem>
                                {/each}
                            </NavigationMenuList>
                        </NavigationMenuRoot>
                    </PopoverContent>
                </Popover>
            {/if}
            <div class="flex items-center gap-6">
                <button
                    onclick={() => window.open("/", "_self")}
                    class="flex items-center space-x-2 text-primary hover:text-primary/90 transition-colors cursor-pointer"
                >
                    <div class="text-2xl">
                        <img class="w-auto h-11 align-middle inline-block select-none" src={LogoImg} alt="TigerRacing purple logo" />
                    </div>
                </button>
                {#if !isMobile}
                    <NavigationMenuRoot class="flex">
                        <NavigationMenuList class="gap-1">
                            {#each NavigationLinks as link, index (index)}
                                <NavigationMenuItem>
                                    <NavigationMenuLink
                                        href={link.href}
                                        onclick={e => {
                                            e.preventDefault();
                                            if (link.href) window.open(link.href, "_blank");
                                        }}
                                        class="text-muted-foreground hover:text-primary font-medium transition-colors cursor-pointer group inline-flex h-10 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50"
                                    >
                                        {link.title}
                                    </NavigationMenuLink>
                                </NavigationMenuItem>
                            {/each}
                        </NavigationMenuList>
                    </NavigationMenuRoot>
                {/if}
            </div>
        </div>
        <div class="flex items-center gap-4">
            <div class="flex items-center gap-2">
                <DropdownMenu>
                    <DropdownMenuTrigger>
                        <Button variant="ghost" size="icon" class="h-9 w-9 relative">
                            <BellIcon class="h-4 w-4" />
                            {#if notificationCount > 0}
                                <Badge class="absolute -top-1 -right-1 h-5 w-5 flex items-center justify-center p-0 text-xs">
                                    {notificationCount > 9 ? "9+" : notificationCount}
                                </Badge>
                            {/if}
                            <span class="sr-only">Notifications</span>
                        </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align="end" class="w-80">
                        <DropdownMenuLabel>Notifications</DropdownMenuLabel>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem onclick={() => false /* onItemClick?.("notification1") */}>
                            <div class="flex flex-col gap-1">
                                <p class="text-sm font-medium">Ricky is a bum</p>
                                <p class="text-xs text-muted-foreground">Just now</p>
                            </div>
                        </DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem onclick={() => window.open("/dashboard", "_self")}>
                            View all notifications
                        </DropdownMenuItem>
                    </DropdownMenuContent>
                </DropdownMenu>
            </div>
            <DropdownMenu>
                <DropdownMenuTrigger>
                    <Button variant="ghost" class="h-9 px-2 py-0 hover:bg-accent hover:text-accent-foreground">
                        <Avatar class="h-7 w-7">
                            <AvatarImage src={userAvatar} alt={userName} />
                            <AvatarFallback class="text-xs">
                                {userName.split(" ").map(n => n[0]).join("")}
                            </AvatarFallback>
                        </Avatar>
                        <ChevronDownIcon class="h-3 w-3 ml-1" />
                        <span class="sr-only">User menu</span>
                    </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" class="w-56">
                    <DropdownMenuLabel>
                        <div class="flex flex-col space-y-1">
                            <p class="text-sm font-medium leading-none">{userName}</p>
                            <p class="text-xs leading-none text-muted-foreground">
                                {userEmail}
                            </p>
                        </div>
                    </DropdownMenuLabel>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem onclick={() => window.open("/dashboard", "_self")}>
                        <Gauge />
                        Dashboard
                    </DropdownMenuItem>
                    <DropdownMenuItem onclick={() => window.open("/profile", "_self")}>
                        <User />
                        Profile
                    </DropdownMenuItem>
                    <DropdownMenuItem onclick={() => window.open("/mail", "_self")}>
                        <Mail />
                        Inbox
                    </DropdownMenuItem>
                    <DropdownMenuItem onclick={() => window.open("/projects", "_self")}>
                        <Folder />
                        Projects
                    </DropdownMenuItem>
                    <DropdownMenuItem onclick={() => window.open("/orders", "_self")}>
                        <ShoppingCart />
                        Orders
                    </DropdownMenuItem>
                    <DropdownMenuItem onclick={() => window.open("/admin", "_self")}>
                        <UserCog />
                        Admin
                    </DropdownMenuItem>
                    <DropdownMenuItem onclick={() => window.open("/settings", "_self")}>
                        <Settings />
                        Settings
                    </DropdownMenuItem>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem onclick={() => window.open("/wiki", "_self")}>
                        <GraduationCap />
                        Wiki
                    </DropdownMenuItem>
                    <DropdownMenuItem onclick={() => window.open("/docs", "_self")}>
                        <FileText />
                        Documentation
                    </DropdownMenuItem>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem onclick={() => window.open("/logout", "_self")}>
                        <LogOut />
                        Sign out
                    </DropdownMenuItem>
                </DropdownMenuContent>
            </DropdownMenu>
        </div>
    </div>
</header>

// frontend/src/components/layout/Navbar.tsx
"use client";

import {
    BellIcon,
    ChevronDownIcon,
    FileText,
    Folder,
    Gauge,
    GraduationCap,
    LogOut,
    Mail,
    Settings,
    ShoppingCart,
    User,
    UserCog
} from "lucide-react";
import {
    forwardRef,
    useEffect,
    useState,
    useRef,
    type HTMLAttributes,
    type ImgHTMLAttributes,
    type ReactElement,
    type SVGAttributes,
    useCallback,
    type ReactNode
} from "react";

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
    NavigationMenu,
    NavigationMenuItem,
    NavigationMenuLink,
    NavigationMenuList
} from "@/components/ui/navigation-menu";
import {
    Popover,
    PopoverContent,
    PopoverTrigger
} from "@/components/ui/popover";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger
} from "@/components/ui/dropdown-menu";

import { cn } from "@/lib/utils";

import LogoImg from "@/assets/img/logos/logo.png";

interface NavbarItem {
    title: string
    href?: string
}

interface NavbarProps extends HTMLAttributes<HTMLElement> {
    logo?: ReactNode
    logoHref?: string
    navigationLinks?: NavbarItem[]
    userName?: string
    userEmail?: string
    userAvatar?: string
    notificationCount?: number
    onNavItemClick?: (href: string) => void
    onNotificationItemClick?: (item: string) => void
    onUserItemClick?: (item: string) => void
}

const NavigationLinks: NavbarItem[] = [];

/**
 * Navbar logo.
 */
const Logo = (props: ImgHTMLAttributes<HTMLImageElement>) => {
    return (
        <img
            className="w-auto h-11 align-middle inline-block select-none"
            src={LogoImg}
            alt="TigerRacing purple logo"
            {...props}
        />
    );
};

const HamburgerIcon = ({ className, ...props }: SVGAttributes<SVGElement>) => (
    <svg
        className={cn("pointer-events-none", className)}
        width={16}
        height={16}
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
    >
        <path
            d="M4 12L20 12"
            className="origin-center -translate-y-[7px] transition-all duration-300 ease-[cubic-bezier(.5,.85,.25,1.1)] group-aria-expanded:translate-x-0 group-aria-expanded:translate-y-0 group-aria-expanded:rotate-315"
        />
        <path
            d="M4 12H20"
            className="origin-center transition-all duration-300 ease-[cubic-bezier(.5,.85,.25,1.8)] group-aria-expanded:rotate-45"
        />
        <path
            d="M4 12H20"
            className="origin-center translate-y-[7px] transition-all duration-300 ease-[cubic-bezier(.5,.85,.25,1.1)] group-aria-expanded:translate-y-0 group-aria-expanded:rotate-135"
        />
    </svg>
);

const NotificationMenu = ({
    notificationCount = 1,
    onItemClick
}: {
    notificationCount?: number
    onItemClick?: (item: string) => void
}) => (
    <DropdownMenu>
        <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon" className="h-9 w-9 relative">
                <BellIcon className="h-4 w-4" />
                {notificationCount > 0 && (
                    <Badge className="absolute -top-1 -right-1 h-5 w-5 flex items-center justify-center p-0 text-xs">
                        {notificationCount > 9 ? "9+" : notificationCount}
                    </Badge>
                )}
                <span className="sr-only">Notifications</span>
            </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-80">
            <DropdownMenuLabel>Notifications</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={() => onItemClick?.("notification1")}>
                <div className="flex flex-col gap-1">
                    <p className="text-sm font-medium">Ricky is a bum</p>
                    <p className="text-xs text-muted-foreground">Just now</p>
                </div>
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={() => onItemClick?.("/dashboard")}>
                View all notifications
            </DropdownMenuItem>
        </DropdownMenuContent>
    </DropdownMenu>
);

const UserMenu = ({
    userName = "Car McCarface",
    userEmail = "cmccarface1@lsu.edu",
    userAvatar,
    onItemClick
}: {
    userName?: string
    userEmail?: string
    userAvatar?: string
    onItemClick?: (item: string) => void
}) => (
    <DropdownMenu>
        <DropdownMenuTrigger asChild>
            <Button variant="ghost" className="h-9 px-2 py-0 hover:bg-accent hover:text-accent-foreground">
                <Avatar className="h-7 w-7">
                    <AvatarImage src={userAvatar} alt={userName} />
                    <AvatarFallback className="text-xs">
                        {userName.split(" ").map(n => n[0]).join("")}
                    </AvatarFallback>
                </Avatar>
                <ChevronDownIcon className="h-3 w-3 ml-1" />
                <span className="sr-only">User menu</span>
            </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-56">
            <DropdownMenuLabel>
                <div className="flex flex-col space-y-1">
                    <p className="text-sm font-medium leading-none">{userName}</p>
                    <p className="text-xs leading-none text-muted-foreground">
                        {userEmail}
                    </p>
                </div>
            </DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={() => onItemClick?.("/dashboard")}>
                <Gauge />
                Dashboard
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => onItemClick?.("/profile")}>
                <User />
                Profile
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => onItemClick?.("/mail")}>
                <Mail />
                Inbox
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => onItemClick?.("/projects")}>
                <Folder />
                Projects
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => onItemClick?.("/orders")}>
                <ShoppingCart />
                Orders
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => onItemClick?.("/admin")}>
                <UserCog />
                Admin
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => onItemClick?.("/settings")}>
                <Settings />
                Settings
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={() => onItemClick?.("/wiki")}>
                <GraduationCap />
                Wiki
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => onItemClick?.("/docs")}>
                <FileText />
                Documentation
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={() => onItemClick?.("/logout")}>
                <LogOut />
                Sign out
            </DropdownMenuItem>
        </DropdownMenuContent>
    </DropdownMenu>
);

const NavbarComponent = forwardRef<HTMLElement, NavbarProps>(
    (
        {
            className,
            logo = <Logo />,
            logoHref = "/",
            navigationLinks = NavigationLinks,
            userName = "Car McCarface",
            userEmail = "cmccar1@lsu.edu",
            userAvatar,
            notificationCount = 0,
            onNavItemClick = (href: string) => window.open(href, "_blank"),
            onNotificationItemClick = (href: string) => window.open(href, "_self"),
            onUserItemClick = (href: string) => window.open(href, "_self"),
            ...props
        },
        ref
    ) => {
        const [isMobile, setIsMobile] = useState(false);
        const containerRef = useRef<HTMLElement>(null);
        useEffect(() => {
            const checkWidth = () => {
                if (containerRef.current) {
                    const width = containerRef.current.offsetWidth;
                    setIsMobile(width < 768); // 768px is md breakpoint
                }
            };
            checkWidth();
            const resizeObserver = new ResizeObserver(checkWidth);
            if (containerRef.current) {
                resizeObserver.observe(containerRef.current);
            }
            return () => {
                resizeObserver.disconnect();
            };
        }, []);
        // Combine refs
        const combinedRef = useCallback((node: HTMLElement | null) => {
            containerRef.current = node;
            if (typeof ref === "function") {
                ref(node);
            } else if (ref) {
                ref.current = node;
            }
        }, [ref]);
        return (
            <header
                ref={combinedRef}
                className={cn(
                    "xl:fixed top-0 z-50 w-full border-b-3 shadow-2xl border-primary bg-background px-4 md:px-6 **:no-underline",
                    className
                )}
                {...props}
            >
                <div className="flex h-16 items-center justify-between gap-4">
                    <div className="flex items-center gap-2">
                        {isMobile && (
                            <Popover>
                                <PopoverTrigger asChild>
                                    <Button
                                        className="group h-9 w-9 hover:bg-accent hover:text-accent-foreground"
                                        variant="ghost"
                                        size="icon"
                                    >
                                        <HamburgerIcon />
                                    </Button>
                                </PopoverTrigger>
                                <PopoverContent align="start" className="w-64 p-1">
                                    <NavigationMenu className="max-w-none">
                                        <NavigationMenuList className="flex-col items-start gap-0">
                                            {navigationLinks.map((link, index) => (
                                                <NavigationMenuItem key={index} className="w-full">
                                                    <button
                                                        onClick={e => {
                                                            e.preventDefault();
                                                            if (onNavItemClick && link.href) onNavItemClick(link.href);
                                                        }}
                                                        className="flex w-full items-center rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground no-underline"
                                                    >
                                                        {link.title}
                                                    </button>
                                                </NavigationMenuItem>
                                            ))}
                                        </NavigationMenuList>
                                    </NavigationMenu>
                                </PopoverContent>
                            </Popover>
                        )}
                        <div className="flex items-center gap-6">
                            <button
                                onClick={() => window.open(logoHref, "_self")}
                                className="flex items-center space-x-2 text-primary hover:text-primary/90 transition-colors cursor-pointer"
                            >
                                <div className="text-2xl">
                                    {logo}
                                </div>
                            </button>
                            {!isMobile && (
                                <NavigationMenu className="flex">
                                    <NavigationMenuList className="gap-1">
                                        {navigationLinks.map((link, index) => (
                                            <NavigationMenuItem key={index}>
                                                <NavigationMenuLink
                                                    href={link.href}
                                                    onClick={e => {
                                                        e.preventDefault();
                                                        if (onNavItemClick && link.href) onNavItemClick(link.href);
                                                    }}
                                                    className="text-muted-foreground hover:text-primary font-medium transition-colors cursor-pointer group inline-flex h-10 w-max items-center justify-center rounded-md bg-background px-4 py-2 text-sm focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50"
                                                >
                                                    {link.title}
                                                </NavigationMenuLink>
                                            </NavigationMenuItem>
                                        ))}
                                    </NavigationMenuList>
                                </NavigationMenu>
                            )}
                        </div>
                    </div>
                    <div className="flex items-center gap-4">
                        <div className="flex items-center gap-2">
                            <NotificationMenu
                                notificationCount={notificationCount}
                                onItemClick={onNotificationItemClick}
                            />
                        </div>
                        <UserMenu
                            userName={userName}
                            userEmail={userEmail}
                            userAvatar={userAvatar}
                            onItemClick={onUserItemClick}
                        />
                    </div>
                </div>
            </header>
        );
    }
);

export default function Navbar (): ReactElement {
    return (
        <NavbarComponent />
    );
};
