// frontend/src/pages/Projects.tsx
import { ProjectCard } from "@/components/projects/ProjectCard.tsx";

export default function Projects () {
    return (
        <div className="min-h-screen bg-white">

            {/* Main content */}
            <main className="px-8 py-6 max-w-[1600px] mx-auto">

                {/* Page header with filters */}
                <div className="mb-6 flex justify-between items-center">
                    <h1 className="text-2xl font-bold text-gray-900">Projects</h1>
                    <div className="flex gap-3 items-center">

                        {/* Search input */}
                        <input
                            type="text"
                            placeholder="Search projects..."
                            className="px-4 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:border-purple-600 w-48"
                        />

                        {/* Status filter */}
                        <select className="px-4 py-2 border border-gray-300 rounded-md text-sm bg-white cursor-pointer focus:outline-none">
                            <option>All Status</option>
                            <option>Active</option>
                            <option>Planning</option>
                            <option>Completed</option>
                            <option>On Hold</option>
                        </select>

                        {/* Priority filter */}
                        <select className="px-4 py-2 border border-gray-300 rounded-md text-sm bg-white cursor-pointer focus:outline-none">
                            <option>All Priorities</option>
                            <option>High Priority</option>
                            <option>Medium Priority</option>
                            <option>Low Priority</option>
                        </select>

                        {/* New project button */}
                        <button
                            style={{ backgroundColor: "#510087" }}
                            className="text-white px-5 py-2 rounded-md text-sm font-semibold flex items-center gap-2"
                        >
                            <span className="text-lg">+</span> New Project
                        </button>
                    </div>
                </div>

                {/* Projects grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    <ProjectCard />
                    <ProjectCard />
                    <ProjectCard />
                    <ProjectCard />
                    <ProjectCard />
                    <ProjectCard />
                </div>
            </main>
        </div>
    );
}

// frontend/src/routes/projects/+page.svelte
<script lang="ts">
    import Plus from "@lucide/svelte/icons/plus";

    import { Button, buttonVariants } from "$lib/components/ui/button";
    import { Dialog, DialogTrigger } from "$lib/components/ui/dialog";
    import {
        Select,
        SelectContent,
        SelectItem,
        SelectTrigger
    } from "$lib/components/ui/select";
    import { Input } from "$lib/components/ui/input";

    import ProjectCard from "$lib/components/pages/projects/dashboard/ProjectCard.svelte";

    import { API } from "$lib/modules/API";

    import { ProjectPriority, ProjectStatus } from "../../../../shared/config/enums";

    const projects = $state<Awaited<ReturnType<API["fetchProjects"]>>["data"]>([
        {
            id: "1",
            title: "Project 1",
            priority: ProjectPriority.High,
            status: ProjectStatus.Draft,
            deadline: "Dec 1, 2025",
            users: ["TD", "CT", "RL"],
            progress: 67
        },
        {
            id: "2",
            title: "Project 2",
            priority: ProjectPriority.Medium,
            status: ProjectStatus.OnHold,
            deadline: "Dec 2, 2025",
            users: ["TD", "CT", "RL"],
            progress: 67
        },
        {
            id: "3",
            title: "Project 3",
            priority: ProjectPriority.Low,
            status: ProjectStatus.Active,
            deadline: "Dec 2, 2025",
            users: ["TD", "CT", "RL"],
            progress: 67
        },
        {
            id: "4",
            title: "Project 4",
            priority: ProjectPriority.High,
            status: ProjectStatus.Completed,
            deadline: "Dec 2, 2025",
            users: ["TD", "CT", "RL"],
            progress: 67
        }
    ]);

    let filters = $state<{
        priority: ProjectPriority | "All Priorities"
        status: ProjectStatus | "All Status"
        name: string
    }>({
        priority: "All Priorities",
        status: "All Status",
        name: ""
    });

</script>

<div class="xl:mt-16.75 px-8 pt-6">
    <Dialog>
        <div class="lg:flex justify-between items-center">
            <h1 class="text-2xl font-bold">Projects</h1>
            <div class="flex flex-col lg:flex-row gap-2 mt-2 lg:mt-0">
                <Input class="lg:w-[300px]!" type="text" placeholder="Search projects..." bind:value={filters.name} autocomplete="off" />
                <Select type="single" name="status-select" bind:value={filters.status}>
                    <SelectTrigger class="w-full lg:w-[180px] bg-background">{filters.status}</SelectTrigger>
                    <SelectContent>
                        <SelectItem label="All Status" value="All Status" disabled={filters.status === "All Status"}>All Status</SelectItem>
                        {#each Object.values(ProjectStatus) as value, i (i)}
                            <SelectItem label={value} {value} disabled={filters.status === value}>{value}</SelectItem>
                        {/each}
                    </SelectContent>
                </Select>
                <Select type="single" name="priority-select" bind:value={filters.priority}>
                    <SelectTrigger class="w-full lg:w-[180px] bg-background">{filters.priority}</SelectTrigger>
                    <SelectContent>
                        <SelectItem label="All Priorities" value="All Priorities" disabled={filters.priority === "All Priorities"}>All Priorities</SelectItem>
                        {#each Object.values(ProjectPriority) as value, i (i)}
                            <SelectItem label={value} {value} disabled={filters.priority === value}>{value}</SelectItem>
                        {/each}
                    </SelectContent>
                </Select>
                <DialogTrigger class={buttonVariants()}>
                    <Plus strokeWidth="3px" />
                    New Project
                </DialogTrigger>
            </div>
        </div>
        <div class="grid grid-cols-1 gap-3 mt-4 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
            {#each projects as project (project.id)}
                <ProjectCard project={project} />
            {/each}
        </div>
    </Dialog>
</div>
