// frontend/src/components/ui/shadcn-components/toggle-group.tsx
"use client";

import * as React from "react";
import * as ToggleGroupPrimitive from "@radix-ui/react-toggle-group";
import { type VariantProps } from "class-variance-authority";

import { cn } from "@/lib/utils";
import { toggleVariants } from "@/components/ui/shadcn-components/toggle";

const ToggleGroupContext = React.createContext<
    VariantProps<typeof toggleVariants>
>({
    size: "default",
    variant: "default"
});

function ToggleGroup ({
    className,
    variant,
    size,
    children,
    ...props
}: React.ComponentProps<typeof ToggleGroupPrimitive.Root>
    & VariantProps<typeof toggleVariants>) {
    return (
        <ToggleGroupPrimitive.Root
            data-slot="toggle-group"
            data-variant={variant}
            data-size={size}
            className={cn(
                "group/toggle-group flex w-fit items-center rounded-md data-[variant=outline]:shadow-xs",
                className
            )}
            {...props}
        >
            <ToggleGroupContext.Provider value={{ variant, size }}>
                {children}
            </ToggleGroupContext.Provider>
        </ToggleGroupPrimitive.Root>
    );
}

function ToggleGroupItem ({
    className,
    children,
    variant,
    size,
    ...props
}: React.ComponentProps<typeof ToggleGroupPrimitive.Item>
    & VariantProps<typeof toggleVariants>) {
    const context = React.useContext(ToggleGroupContext);

    return (
        <ToggleGroupPrimitive.Item
            data-slot="toggle-group-item"
            data-variant={context.variant || variant}
            data-size={context.size || size}
            className={cn(
                toggleVariants({
                    variant: context.variant || variant,
                    size: context.size || size
                }),
                "min-w-0 flex-1 shrink-0 rounded-none shadow-none first:rounded-l-md last:rounded-r-md focus:z-10 focus-visible:z-10 data-[variant=outline]:border-l-0 data-[variant=outline]:first:border-l",
                className
            )}
            {...props}
        >
            {children}
        </ToggleGroupPrimitive.Item>
    );
}

export { ToggleGroup, ToggleGroupItem };

// frontend/src/lib/components/ui/toggle-group/toggle-group.svelte
<script lang="ts" module>
    import { getContext, setContext } from "svelte";
    import type { VariantProps } from "tailwind-variants";
    import { toggleVariants } from "$lib/components/ui/toggle/index.js";

    type ToggleVariants = VariantProps<typeof toggleVariants>;

    interface ToggleGroupContext extends ToggleVariants {
        spacing?: number
    }

    export function setToggleGroupCtx (props: ToggleGroupContext) {
        setContext("toggleGroup", props);
    }

    export function getToggleGroupCtx () {
        return getContext<Required<ToggleGroupContext>>("toggleGroup");
    }
</script>

<script lang="ts">
    import { ToggleGroup as ToggleGroupPrimitive } from "bits-ui";
    import { cn } from "$lib/utils.js";

    let {
        ref = $bindable(null),
        value = $bindable(),
        class: className,
        size = "default",
        spacing = 0,
        variant = "default",
        ...restProps
    }: ToggleGroupPrimitive.RootProps & ToggleVariants & { spacing?: number } = $props();

    setToggleGroupCtx({
        variant,
        size,
        spacing
    });
</script>

<!--
Discriminated Unions + Destructing (required for bindable) do not
get along, so we shut typescript up by casting `value` to `never`.
-->
<ToggleGroupPrimitive.Root
    bind:value={value as never}
    bind:ref
    data-slot="toggle-group"
    data-variant={variant}
    data-size={size}
    data-spacing={spacing}
    style={`--gap: ${spacing}`}
    class={cn(
        "group/toggle-group flex w-fit items-center gap-[--spacing(var(--gap))] rounded-md data-[spacing=default]:data-[variant=outline]:shadow-xs",
        className
    )}
    {...restProps}
/>
