// frontend/src/lib/components/pages/admin/SearchBar.svelte
<script lang="ts">
    import {
        FunnelIcon,
        GalleryHorizontalIcon,
        SearchIcon,
        TableProperties
    } from "@lucide/svelte";

    import { Button } from "$lib/components/ui/button";
    import {
        DropdownMenu,
        DropdownMenuContent,
        DropdownMenuTrigger
    } from "$lib/components/ui/dropdown-menu";
    import { Input } from "$lib/components/ui/input";

    import FilterDropdown from "./FilterDropdown.svelte";
    import { ViewMode, type AdminProps } from "./types";

    let {
        viewMode = $bindable(),
        sortOrder = $bindable(),
        filters = $bindable(),
        filteredCount
    }: Pick<AdminProps, "viewMode" | "filters" | "sortOrder" | "filteredCount"> = $props();

</script>

<div class="bg-background rounded-xl border-b px-4 md:px-6 **:no-underline">
    <div class="flex h-16 items-center justify-between gap-4">
        <!-- Left side -->
        <div class="flex flex-1 items-center gap-2">
            <DropdownMenu>
                <DropdownMenuTrigger>
                    {#snippet child({ props })}
                        <Button
                            {...props}
                            size="icon-lg"
                            variant="ghost"
                            class="text-muted-foreground rounded-full shadow-none"
                            aria-label="Open search menu"
                            onclick={e => e.preventDefault()}
                        >
                            <FunnelIcon class="scale-115" aria-hidden="true" />
                        </Button>
                    {/snippet}
                </DropdownMenuTrigger>
                <DropdownMenuContent class="max-w-fit" align="start">
                    <FilterDropdown
                        bind:sortOrder={sortOrder}
                        bind:filters={filters}
                        filteredCount={filteredCount}
                    />
                </DropdownMenuContent>
            </DropdownMenu>
            <div class="relative flex-1">
                <Input
                    id="admin-search-name"
                    class="peer w-full max-w-xl ps-8 pe-2"
                    placeholder="Search for members..."
                    type="search"
                    autocomplete="off"
                    bind:value={filters.name}
                />
                <div class="text-muted-foreground/80 pointer-events-none absolute inset-y-0 start-0 flex items-center justify-center ps-2 peer-disabled:opacity-50">
                    <SearchIcon size={16} />
                </div>
            </div>
        </div>

        <!-- Right side -->
        <div class="flex items-center gap-4">
            <Button size="icon" variant="ghost" class="rounded-full" aria-label="Toggle layout view" onclick={() => viewMode = viewMode === ViewMode.Gallery ? ViewMode.List : ViewMode.Gallery}>
                {#if viewMode === ViewMode.Gallery}
                    <GalleryHorizontalIcon />
                {:else}
                    <TableProperties />
                {/if}
            </Button>
        </div>
    </div>
</div>

// frontend/src/components/ui/adminPortal/SearchBar/shadcn-io/SearchBar/index.tsx
'use client';

import * as React from 'react';
import { useId, useState, useRef, useEffect } from 'react';

import { data, type Member } from "@/components/dummyData/members";
import { TableProperties, FunnelIcon, SearchIcon, GalleryHorizontalIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';
import type { System, Subsystem } from "@/components/dummyData/members";

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

import FilterDropdown from "@/components/ui/adminPortal/SearchBar/FilterDropdown";

export interface SearchBarProps extends React.HTMLAttributes<HTMLElement> {
  searchPlaceholder?: string;
  searchValue?: string;
  view: "column" | "gallery";
  setView: React.Dispatch<React.SetStateAction<"column" | "gallery">>;
  sortOrder: "asc" | "desc";
  setSortOrder: React.Dispatch<React.SetStateAction<"asc" | "desc">>;
  onFiltersChange: (filteredMembers: Member[]) => void;
  onSearchChange?: (value: string) => void;
  onDropdownSelect: (memberId: string) => void; 
}

export const SearchBar = React.forwardRef<HTMLElement, SearchBarProps>(
  (
    {
      className,
      searchPlaceholder = 'Search for members...',
      view,
      setView,
      sortOrder,
      setSortOrder,
      onFiltersChange,
      onDropdownSelect,
      ...props
    },
    ref
  ) => {
    const id = useId();

    // Search and filtering state
    const [searchValue, setSearchValue] = useState("");
    const [filteredItems, setFilteredItems] = useState<Member[]>([]);
    const [isDropdownOpen, setIsDropdownOpen] = useState(false);
    const dropdownRef = useRef<HTMLDivElement>(null);

    const handleSearch = (event: React.ChangeEvent<HTMLInputElement>) => {
      const value = event.target.value;
      setSearchValue(value);

      const filtered = data.filter((member) =>
        member.name.toLowerCase().includes(value.toLowerCase())
      );
      setFilteredItems(filtered);
      if (value.length > 0) setIsDropdownOpen(true);
    };

    // Use effects for clicking outside
    useEffect(() => {
      function handleClickOutside(event: MouseEvent) {
        if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
          setIsDropdownOpen(false);
        }
      }
      if (isDropdownOpen) document.addEventListener('mousedown', handleClickOutside);
      return () => document.removeEventListener('mousedown', handleClickOutside);
    }, [isDropdownOpen]);

    const [filteredCount, setFilteredCount] = useState(0);
    const [filters, setFilters] = useState({
      selectedSystems: [] as System[],
      selectedSubsystems: [] as Subsystem[],
      selectedYears: [] as Member["grad"][],
    });

    return (
      <header
        ref={ref}
        className={cn('px-4 md:px-6 [&_*]:no-underline', className)}
        {...props}
      >
        <div className="flex h-16 items-center justify-between gap-4 pt-2">
          {/* Left side: Filter button + input */}
          <div className="flex items-center gap-2 flex-1 z-10">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  size="icon"
                  variant="ghost"
                  className="text-muted-foreground h-10 w-10 rounded-full shadow-none"
                  aria-label="Open search menu"
                  onClick={(e) => e.preventDefault()}
                >
                  <FunnelIcon className="scale-115" aria-hidden="true" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="max-w-fit" align="start">
                <FilterDropdown
                  filters={filters}
                  setFilters={setFilters}
                  filteredCount={filteredCount}
                  setFilteredCount={setFilteredCount}
                  sortOrder={sortOrder}
                  setSortOrder={setSortOrder}
                  onFiltersChange={onFiltersChange}
                />
              </DropdownMenuContent>
            </DropdownMenu>

            {/* Input and Search */}
            <div className="relative flex-1 max-w-lg" ref={dropdownRef}>
              <Input
                id={`input-${id}`}
                className="peer h-12 w-full pl-8 pr-2 text-lg placeholder:text-base md:placeholder:text-lg"
                placeholder={searchPlaceholder}
                type="search"
                value={searchValue}
                onChange={handleSearch}
                onFocus={() => searchValue && setIsDropdownOpen(true)}
                autoComplete='off'
              />
              <div className="absolute inset-y-0 left-0 flex items-center pl-2 text-muted-foreground/80">
                <SearchIcon size={16} />
              </div>

              {isDropdownOpen && searchValue && (
                <div className="absolute mt-1 top-full w-full shadow bg-white">
                  {filteredItems.length > 0 ? (
                    filteredItems.map((member) => (
                      <div
                        key={member.id}
                        className="px-4 py-2 border-b border-muted-foreground/30 rounded hover:bg-accent cursor-pointer"
                        onClick={() => {
                          onDropdownSelect(member.id);
                          setIsDropdownOpen(false);
                        }}
                      >
                        <ul>
                          <li>{member.name}</li>
                        </ul>
                      </div>
                    ))
                  ) : (
                    <div className="px-4 py-2 text-muted-foreground">
                      Uh oh! No members found.
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>

          {/* Right side: Layout button */}
          <Button
            size="icon"
            variant="ghost"
            className="text-muted-foreground w-10 h-10 rounded-full shadow-none"
            aria-label="Open layout view"
            onClick={() => view === "column" ? setView("gallery") : setView("column")}
          >
            {view === "column" ? (
              <GalleryHorizontalIcon className="scale-115" aria-hidden />
            ) : (
              <TableProperties className="scale-115" aria-hidden="true" />
            )}
          </Button>
        </div>
      </header>
    );
  }
);

SearchBar.displayName = 'SearchBar';
