// frontend/src/lib/components/pages/admin/UserDropdown.svelte
<script lang="ts">
    import Ellipsis from "@lucide/svelte/icons/ellipsis";

    import {
        AlertDialog,
        AlertDialogAction,
        AlertDialogCancel,
        AlertDialogContent,
        AlertDialogDescription,
        AlertDialogFooter,
        AlertDialogHeader,
        AlertDialogTitle
    } from "$lib/components/ui/alert-dialog";
    import { Button } from "$lib/components/ui/button";
    import {
        DropdownMenu,
        DropdownMenuContent,
        DropdownMenuItem,
        DropdownMenuSeparator,
        DropdownMenuLabel,
        DropdownMenuTrigger
    } from "$lib/components/ui/dropdown-menu";

    import { api } from "$lib/modules/API";
    import type { Unpacked } from "$lib/utils";
    import type { AdminProps } from "./types";

    const { user }: { user: Unpacked<AdminProps["users"]> } = $props();
    let open = $state(false);
</script>

<DropdownMenu>
    <DropdownMenuTrigger>
        {#snippet child({ props })}
            <Button {...props} variant="ghost" class="h-8 w-8 p-0 hover:bg-primary hover:text-white hover:border-primary">
                <span class="sr-only">Open menu</span>
                <Ellipsis />
            </Button>
        {/snippet}
    </DropdownMenuTrigger>
    <DropdownMenuContent align="end" class="bg-white">
        <DropdownMenuLabel class="font-manrope font-extrabold">
            Moderation
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem onclick={() => open = true}>
            Delete
        </DropdownMenuItem>
    </DropdownMenuContent>
</DropdownMenu>

<AlertDialog open={open} onOpenChange={val => open = val}>
    <AlertDialogContent>
        <AlertDialogHeader>
            <AlertDialogTitle class="font-manrope h1 text-center">
                Are you absolutely sure you want to delete {user.name}?
            </AlertDialogTitle>
            <AlertDialogDescription class="font-sora text-gray-600 text-center">
                This action cannot be undone. This will permanently delete {user.name}'s
                account and remove their data from the servers.
            </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter class="items-center font-sora">
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction onclick={() => api.deleteUser(user.id)}>
                Continue
            </AlertDialogAction>
        </AlertDialogFooter>
    </AlertDialogContent>
</AlertDialog>

// frontend/src/components/pages/admin/UserDropdown.tsx
import { useState, type ReactElement } from "react";
import { MoreHorizontal } from "lucide-react";

import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSeparator,
    DropdownMenuLabel,
    DropdownMenuTrigger
} from "@/components/ui/dropdown-menu";

import type { TRAPI } from "../../../../../shared/typings/api.js";

interface UserDropdownProps {
    user: TRAPI.User
    deleteUser: (userId: string) => void
}

export default function UserDropdown ({ user, deleteUser }: UserDropdownProps): ReactElement {
    const [open, setOpen] = useState(false);
    return (
        <>
            <DropdownMenu>
                <DropdownMenuTrigger asChild>
                    <Button variant="ghost" className="h-8 w-8 p-0 hover:bg-primary hover:text-white hover:border-primary">
                        <span className="sr-only">Open menu</span>
                        <MoreHorizontal />
                    </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="bg-white">
                    <DropdownMenuLabel className="font-manrope font-extrabold">
                        Moderate Member
                    </DropdownMenuLabel>
                    <DropdownMenuSeparator />
                    <DropdownMenuItem onClick={() => setOpen(true)}>
                        Kick / Ban
                    </DropdownMenuItem>
                </DropdownMenuContent>
            </DropdownMenu>

            <AlertDialog open={open} onOpenChange={setOpen}>
                <AlertDialogContent>
                    <AlertDialogHeader>
                        <AlertDialogTitle className="font-manrope h1 text-center">
                            Are you absolutely sure you want to delete {user.name}?
                        </AlertDialogTitle>
                        <AlertDialogDescription className="font-sora text-gray-600 text-center">
                            This action cannot be undone. This will permanently delete {user.name}'s
                            account and remove their data from the servers.
                        </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter className="items-center font-sora">
                        <AlertDialogCancel>Cancel</AlertDialogCancel>
                        <AlertDialogAction onClick={() => deleteUser(user.id)}>
                            Continue
                        </AlertDialogAction>
                    </AlertDialogFooter>
                </AlertDialogContent>
            </AlertDialog>
        </>
    );
}
