// frontend/src/lib/components/ui/spinner/spinner.svelte
<script lang="ts">
    import { cn } from "$lib/utils.js";
    import Loader2Icon from "@lucide/svelte/icons/loader-2";
    import type { ComponentProps } from "svelte";

    let { class: className, ...restProps }: ComponentProps<typeof Loader2Icon> = $props();
</script>

<Loader2Icon
    role="status"
    aria-label="Loading"
    class={cn("size-4 animate-spin", className)}
    {...restProps}
/>

// frontend/src/components/ui/spinner.tsx
import { Loader2Icon } from "lucide-react";

import { cn } from "@/lib/utils";

function Spinner ({ className, ...props }: React.ComponentProps<"svg">) {
    return (
        <Loader2Icon
            role="status"
            aria-label="Loading"
            className={cn("size-4 animate-spin", className)}
            {...props}
        />
    );
}

export { Spinner };
