// frontend/src/components/ui/shadcn-components/toggle.tsx
"use client";

import * as React from "react";
import * as TogglePrimitive from "@radix-ui/react-toggle";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@/lib/utils";

const toggleVariants = cva(
    "inline-flex items-center justify-center gap-2 rounded-md text-sm font-medium hover:bg-muted hover:text-muted-foreground disabled:pointer-events-none disabled:opacity-50 data-[state=on]:bg-accent data-[state=on]:text-accent-foreground [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4 [&_svg]:shrink-0 focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] outline-none transition-[color,box-shadow] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive whitespace-nowrap",
    {
        variants: {
            variant: {
                default: "bg-transparent",
                outline:
          "border border-input bg-transparent shadow-xs hover:bg-accent hover:text-accent-foreground"
            },
            size: {
                default: "h-9 px-2 min-w-9",
                sm: "h-8 px-1.5 min-w-8",
                lg: "h-10 px-2.5 min-w-10"
            }
        },
        defaultVariants: {
            variant: "default",
            size: "default"
        }
    }
);

function Toggle ({
    className,
    variant,
    size,
    ...props
}: React.ComponentProps<typeof TogglePrimitive.Root>
    & VariantProps<typeof toggleVariants>) {
    return (
        <TogglePrimitive.Root
            data-slot="toggle"
            className={cn(toggleVariants({ variant, size, className }))}
            {...props}
        />
    );
}

export { Toggle, toggleVariants };

// frontend/src/lib/components/ui/toggle/toggle.svelte
<script lang="ts" module>
    import { type VariantProps, tv } from "tailwind-variants";

    export const toggleVariants = tv({
        base: "hover:bg-muted hover:text-muted-foreground data-[state=on]:bg-accent data-[state=on]:text-accent-foreground focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive inline-flex items-center justify-center gap-2 rounded-md text-sm font-medium whitespace-nowrap transition-[color,box-shadow] outline-none focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
        variants: {
            variant: {
                default: "bg-transparent",
                outline:
                    "border-input hover:bg-accent hover:text-accent-foreground border bg-transparent shadow-xs"
            },
            size: {
                default: "h-9 min-w-9 px-2",
                sm: "h-8 min-w-8 px-1.5",
                lg: "h-10 min-w-10 px-2.5"
            }
        },
        defaultVariants: {
            variant: "default",
            size: "default"
        }
    });

    export type ToggleVariant = VariantProps<typeof toggleVariants>["variant"];
    export type ToggleSize = VariantProps<typeof toggleVariants>["size"];
    export type ToggleVariants = VariantProps<typeof toggleVariants>;
</script>

<script lang="ts">
    import { Toggle as TogglePrimitive } from "bits-ui";
    import { cn } from "$lib/utils.js";

    let {
        ref = $bindable(null),
        pressed = $bindable(false),
        class: className,
        size = "default",
        variant = "default",
        ...restProps
    }: TogglePrimitive.RootProps & {
        variant?: ToggleVariant
        size?: ToggleSize
    } = $props();
</script>

<TogglePrimitive.Root
    bind:ref
    bind:pressed
    data-slot="toggle"
    class={cn(toggleVariants({ variant, size }), className)}
    {...restProps}
/>
