// frontend/src/components/ui/admin/SearchBar.tsx
"use client";

import {
    useEffect,
    useId,
    useRef,
    useState,
    type ChangeEvent,
    type Dispatch,
    type HTMLAttributes,
    type ReactElement,
    type SetStateAction
} from "react";
import {
    FunnelIcon,
    GalleryHorizontalIcon,
    SearchIcon,
    TableProperties
} from "lucide-react";

import { Button } from "@/components/ui/button";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuTrigger
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";

import FilterDropdown from "./FilterDropdown";

import {
    data,
    type Member,
    type Subsystem,
    type System
} from "@/lib/dummyData/members";

export interface SearchBarProps extends HTMLAttributes<HTMLElement> {
    view: "column" | "gallery"
    sortOrder: "asc" | "desc"
    setView: Dispatch<SetStateAction<SearchBarProps["view"]>>
    setSortOrder: Dispatch<SetStateAction<SearchBarProps["sortOrder"]>>
    onFilterChange: (filteredMembers: Member[]) => void
    onSearchChange: (filteredMembers: Member[]) => void
    onDropdownSelect: (memberId: string) => void
}

export default function SearchBar (props: SearchBarProps): ReactElement<SearchBarProps> {
    const id = useId();

    const [searchValue, setSearchValue] = useState("");
    const [isDropdownOpen, setIsDropdownOpen] = useState(false);
    const dropdownRef = useRef<HTMLDivElement>(null);

    const handleSearch = (event: ChangeEvent<HTMLInputElement>) => {
        const value = event.target.value;
        setSearchValue(value);

        const filtered = data.filter(member => member.name.toLowerCase().includes(value.toLowerCase()));
        props.onSearchChange(filtered);

        if (value.length > 0) setIsDropdownOpen(true);
    };

    // Dismiss the dropdown when clicking outside.
    // NOTE: This isn't very performant.
    useEffect(() => {
        function handleClickOutside (event: MouseEvent) {
            if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
                setIsDropdownOpen(false);
            }
        }

        if (isDropdownOpen) document.addEventListener("mousedown", handleClickOutside);
        return () => document.removeEventListener("mousedown", handleClickOutside);
    }, [isDropdownOpen]);

    const [filteredCount, setFilteredCount] = useState(0);
    const [filters, setFilters] = useState<{ systems: System[], subsystems: Subsystem[], years: Array<Member["grad"]> }>({
        systems: [],
        subsystems: [],
        years: []
    });

    return (
        <div className="bg-background rounded-xl border-b px-4 md:px-6 [&_*]:no-underline">
            <div className="flex h-16 items-center justify-between gap-4">
                {/* Left side */}
                <div className="flex flex-1 items-center gap-2">
                    <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                            <Button
                                size="icon-lg"
                                variant="ghost"
                                className="text-muted-foreground rounded-full shadow-none"
                                aria-label="Open search menu"
                                onClick={e => e.preventDefault()}
                            >
                                <FunnelIcon className="scale-115" aria-hidden="true" />
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent className="max-w-fit" align="start">
                            <FilterDropdown
                                filters={filters}
                                setFilters={setFilters}
                                filteredCount={filteredCount}
                                setFilteredCount={setFilteredCount}
                                sortOrder={props.sortOrder}
                                setSortOrder={props.setSortOrder}
                                onFiltersChange={props.onFilterChange}
                            />
                        </DropdownMenuContent>
                    </DropdownMenu>
                    <div className="relative flex-1">
                        <Input
                            id={`input-${id}`}
                            className="peer w-full max-w-xl ps-8 pe-2"
                            placeholder="Search for members..."
                            type="search"
                            value={searchValue}
                            onChange={handleSearch}
                        />
                        <div className="text-muted-foreground/80 pointer-events-none absolute inset-y-0 start-0 flex items-center justify-center ps-2 peer-disabled:opacity-50">
                            <SearchIcon size={16} />
                        </div>
                    </div>
                </div>

                {/* Right side */}
                <div className="flex items-center gap-4">
                    <Button size="icon" variant="ghost" className="rounded-full" aria-label="Toggle layout view" onClick={() => props.setView(props.view === "column" ? "gallery" : "column")}>
                        {props.view === "column"
                            ? <GalleryHorizontalIcon aria-hidden={true} />
                            : <TableProperties aria-hidden={true} />
                        }
                    </Button>
                </div>
            </div>
        </div>
    );
}

// frontend/src/lib/components/pages/admin/SearchBar.svelte
<script lang="ts">
    import {
        FunnelIcon,
        GalleryHorizontalIcon,
        SearchIcon,
        TableProperties
    } from "@lucide/svelte";

    import { Button } from "$lib/components/ui/button";
    import {
        DropdownMenu,
        DropdownMenuContent,
        DropdownMenuTrigger
    } from "$lib/components/ui/dropdown-menu";
    import { Input } from "$lib/components/ui/input";

    import FilterDropdown from "./FilterDropdown.svelte";
    import { ViewMode, type AdminProps } from "./types";

    let {
        viewMode = $bindable(),
        sortOrder = $bindable(),
        filters = $bindable(),
        filteredCount
    }: Pick<AdminProps, "viewMode" | "filters" | "sortOrder" | "filteredCount"> = $props();

</script>

<div class="bg-background rounded-xl border-b px-4 md:px-6 **:no-underline">
    <div class="flex h-16 items-center justify-between gap-4">
        <!-- Left side -->
        <div class="flex flex-1 items-center gap-2">
            <DropdownMenu>
                <DropdownMenuTrigger>
                    {#snippet child({ props })}
                        <Button
                            {...props}
                            size="icon-lg"
                            variant="ghost"
                            class="text-muted-foreground rounded-full shadow-none"
                            aria-label="Open search menu"
                            onclick={e => e.preventDefault()}
                        >
                            <FunnelIcon class="scale-115" aria-hidden="true" />
                        </Button>
                    {/snippet}
                </DropdownMenuTrigger>
                <DropdownMenuContent class="max-w-fit" align="start">
                    <FilterDropdown
                        bind:sortOrder={sortOrder}
                        bind:filters={filters}
                        filteredCount={filteredCount}
                    />
                </DropdownMenuContent>
            </DropdownMenu>
            <div class="relative flex-1">
                <Input
                    id="admin-search-name"
                    class="peer w-full max-w-xl ps-8 pe-2"
                    placeholder="Search for members..."
                    type="search"
                    autocomplete="off"
                    bind:value={filters.name}
                />
                <div class="text-muted-foreground/80 pointer-events-none absolute inset-y-0 start-0 flex items-center justify-center ps-2 peer-disabled:opacity-50">
                    <SearchIcon size={16} />
                </div>
            </div>
        </div>

        <!-- Right side -->
        <div class="flex items-center gap-4">
            <Button size="icon" variant="ghost" class="rounded-full" aria-label="Toggle layout view" onclick={() => viewMode = viewMode === ViewMode.Gallery ? ViewMode.List : ViewMode.Gallery}>
                {#if viewMode === ViewMode.Gallery}
                    <GalleryHorizontalIcon />
                {:else}
                    <TableProperties />
                {/if}
            </Button>
        </div>
    </div>
</div>
